Flowpack:
  ElasticSearch:
    ContentRepositoryAdaptor:
      driver:
        version: '5.x'
        mapping:
          '1.x':
            query:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version1\Query\FilteredQuery'
              arguments:
                request: &request_version1
                  query:
                    filtered:
                      query:
                        bool:
                          must:
                          - match_all: {  }
                      filter:
                        bool:
                          must: {  }
                          should: {  }
                          must_not:
                          - term:
                              _hidden: true
                          - range:
                              _hiddenBeforeDateTime:
                                gt: now
                          - range:
                              _hiddenAfterDateTime:
                                lt: now
                  fields:
                  - __path
                unsupportedFieldsInCountRequest: &unsupportedFieldsInCountRequest_version1
                - 'fields'
                - 'sort'
                - 'from'
                - 'size'
                - 'highlight'
                - 'aggs'
                - 'aggregations'
                - 'suggest'

            document:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version1\DocumentDriver'
            indexer:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version1\IndexerDriver'
            indexManagement:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version1\IndexDriver'
            request:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version1\RequestDriver'
            system:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version1\SystemDriver'
            nodeTypeMappingBuilder:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version1\Mapping\NodeTypeMappingBuilder'

          '2.x':
            query:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version2\Query\FilteredQuery'
              arguments:
                request:
                  <<: *request_version1
                unsupportedFieldsInCountRequest:
                  <<: *unsupportedFieldsInCountRequest_version1
            document:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version2\DocumentDriver'
            indexer:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version2\IndexerDriver'
            indexManagement:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version2\IndexDriver'
            request:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version2\RequestDriver'
            system:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version2\SystemDriver'
            nodeTypeMappingBuilder:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version2\Mapping\NodeTypeMappingBuilder'


Neos:
  ContentRepository:
    Search:

      # API. If set to FALSE, only index the "live" workspace and not user workspaces.
      # If you only index the live workspace, Search will not work for your editors in the user workspaces.
      # Furthermore, if you heavily rely on Search for collecting content, this might be strange for editors to
      # work with -- as unpublished changes are not indexed right away.
      indexAllWorkspaces: true

      elasticSearch:

        # API. name of the Elasticsearch index to use. Will create many indices prefixed by this indexName.
        indexName: typo3cr

        # configuration of the ElasticSearch logfile
        log:
          backendOptions:
            fileBackend:
              logFileURL: '%FLOW_PATH_DATA%Logs/ElasticSearch.log'
              createParentDirectories: true
              severityThreshold: '%LOG_DEBUG%'
              maximumLogFileSize: 10485760
              logFilesToKeep: 1
              logMessageOrigin: false

            ansiConsoleBackend:
              disableAnsi: false

      defaultConfigurationPerType:

        string:
          elasticSearchMapping:
            type: string

        boolean:
          elasticSearchMapping:
            type: boolean

        integer:
          elasticSearchMapping:
            type: integer

        DateTime:
          elasticSearchMapping:
            type: date
            format: 'date_time_no_millis'

        'Neos\Media\Domain\Model\Asset':
          elasticSearchMapping: '' # deliberately don't map or index this

        'array<Neos\Media\Domain\Model\Asset>':
          elasticSearchMapping: '' # deliberately don't map or index this

        'Neos\Media\Domain\Model\ImageInterface':
          elasticSearchMapping: '' # deliberately don't map or index this

        'references':
          elasticSearchMapping:
            type: string # an array of strings, to be precise
            index: not_analyzed

        'reference':
          elasticSearchMapping:
            type: string
            index: not_analyzed

  Fusion:
    defaultContext:
      SearchResult: Flowpack\ElasticSearch\ContentRepositoryAdaptor\Eel\SearchResultHelper
